### ISSUE TITLE
Some DemARKs depend on deprecated cstwMPC HARK code

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/DemARK#115]
The cstwMPC  implementation in HARK is deprecated:
https://github.com/econ-ark/HARK/issues/449

This means that it is not being maintained in its current form.

But some DemARKs depend on this code in HARK. These DemARKs are:
 - Micro-and-Macro-Implications-of-Very-Impatient-HHs
 - Structural-Estimates-From-Empirical-MPCs-Fagereng-et-al
 - Uncertainty and Saving in Partial Equilibrium

**Comment by sbenthall** [comment]
Some of these can now use the HARK datasets functionality

**Comment by MridulS** [comment]
Uncertainty and Saving in Partial Equilibrium depends on cstwMPC code  https://github.com/econ-ark/DemARK/issues/117

Others are already fixed, closing this.
