### ISSUE TITLE
404 on Gentle Intro?

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/DemARK#118]
I haven't tried the other notebooks, but I'm getting a 404 error when launching the first part of Gentle Intro.

**Comment by llorracc** [comment]
Per a (forgettable) exchange a few months ago: It has been split into two notebooks, one containing the perfect foresight stuff which is really focused on teaching HARK/python, and one on BufferStock stuff which is partly about HARK/python and partly economics.  The original one has been put in HARK/examples as part of the documentation.

**Comment by MridulS** [comment]
The correct link should be https://mybinder.org/v2/gh/econ-ark/DemARK/master?filepath=notebooks/Gentle-Intro-To-HARK-PerfForesightCRRA.ipynb everywhere now, I've updated README for HARK with the correct link. If there are other places with old links we should update them.

**Comment by MridulS** [comment]
The links in documentation and HARK README has been updated.
