### ISSUE TITLE
LifeCycleModel notebook question

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/DemARK#121]
I'm trying to update the DemARKs to make them work with the most recent HARK release.

I'm confused by something in this notebook and I wonder if somebody could explain what's going on:

https://github.com/econ-ark/DemARK/blob/master/notebooks/LifeCycleModelTheoryVsData.ipynb

These are the tracked variables on LifecyclePop:
```
LifeCyclePop.track_vars = ['aNrmNow','pLvlNow','mNrmNow','cNrmNow','TranShkNow']
```
But in cell [9] there is the expression:
```
aGro41=LifeCyclePop.aLvlNow_hist[41]/LifeCyclePop.aLvlNow_hist[40]
```
How could that cell have been evaluated, if aLvlNow was not a tracked variable?

**Comment by mnwhite** [comment]
It was constructed 1 line above that, apparently.

**Comment by sbenthall** [comment]
ah dumb question thank you.
