### ISSUE TITLE
requirements.txt requires matplotlib 2.1.2 which is not compatible with python 3.8

### ISSUE THREAD

**Issue by llorracc** [econ-ark/DemARK#128]
I doubt that anything would break if we updated the requirement to a later version of matplotlib.

**Comment by MridulS** [comment]
requirements.txt in this repo isn't pegged to any version of matplotlib, it will always download the latest one.

https://github.com/econ-ark/DemARK/blob/master/binder/requirements.txt

**Comment by llorracc** [comment]
Sorry, it was the REMARK not the DemARK binder file.  See REMARK for the issue there.
