### ISSUE TITLE
pytest --nbva-lax in notebooks generates errors -- see below

### ISSUE THREAD

**Issue by ccarrollATjhuecon** [econ-ark/DemARK#134]
=============================== short test summary info ===============================
FAILED Alternative-Combos-Of-Parameter-Values.ipynb::Cell 0
FAILED Alternative-Combos-Of-Parameter-Values.ipynb::Cell 1
FAILED Alternative-Combos-Of-Parameter-Values.ipynb::Cell 2
FAILED Alternative-Combos-Of-Parameter-Values.ipynb::Cell 3
FAILED Alternative-Combos-Of-Parameter-Values.ipynb::Cell 4
FAILED Alternative-Combos-Of-Parameter-Values.ipynb::Cell 6
FAILED ChangeLiqConstr.ipynb::Cell 0
FAILED ChangeLiqConstr.ipynb::Cell 1
FAILED ChangeLiqConstr.ipynb::Cell 2
FAILED Chinese-Growth.ipynb::Cell 4
FAILED Chinese-Growth.ipynb::Cell 5
FAILED Chinese-Growth.ipynb::Cell 6
FAILED Chinese-Growth.ipynb::Cell 7
FAILED Chinese-Growth.ipynb::Cell 8
FAILED Chinese-Growth.ipynb::Cell 9
FAILED Chinese-Growth.ipynb::Cell 10
FAILED DCEGM-Upper-Envelope.ipynb::Cell 1
FAILED DCEGM-Upper-Envelope.ipynb::Cell 5
FAILED DCEGM-Upper-Envelope.ipynb::Cell 6
FAILED DCEGM-Upper-Envelope.ipynb::Cell 7
FAILED DCEGM-Upper-Envelope.ipynb::Cell 8
FAILED DCEGM-Upper-Envelope.ipynb::Cell 9
FAILED DCEGM-Upper-Envelope.ipynb::Cell 10
FAILED DCEGM-Upper-Envelope.ipynb::Cell 11
FAILED DCEGM-Upper-Envelope.ipynb::Cell 12
FAILED DCEGM-Upper-Envelope.ipynb::Cell 13
FAILED DCEGM-Upper-Envelope.ipynb::Cell 14
FAILED DCEGM-Upper-Envelope.ipynb::Cell 15
FAILED DCEGM-Upper-Envelope.ipynb::Cell 16
FAILED DCEGM-Upper-Envelope.ipynb::Cell 17
FAILED DiamondOLG.ipynb::Cell 0
FAILED DiamondOLG.ipynb::Cell 3
FAILED FisherTwoPeriod.ipynb::Cell 0
FAILED FisherTwoPeriod.ipynb::Cell 2
FAILED FisherTwoPeriod.ipynb::Cell 3
FAILED FisherTwoPeriod.ipynb::Cell 5
FAILED FisherTwoPeriod.ipynb::Cell 6
FAILED FisherTwoPeriod.ipynb::Cell 8
FAILED FisherTwoPeriod.ipynb::Cell 9
FAILED Gentle-Intro-To-HARK-Buffer-Stock-Model.ipynb::Cell 0
FAILED Gentle-Intro-To-HARK-Buffer-Stock-Model.ipynb::Cell 2
FAILED Gentle-Intro-To-HARK-Buffer-Stock-Model.ipynb::Cell 3
FAILED Gentle-Intro-To-HARK-Buffer-Stock-Model.ipynb::Cell 4
FAILED Gentle-Intro-To-HARK-Buffer-Stock-Model.ipynb::Cell 5
FAILED Gentle-Intro-To-HARK-Buffer-Stock-Model.ipynb::Cell 6
FAILED Gentle-Intro-To-HARK-Buffer-Stock-Model.ipynb::Cell 7
FAILED Gentle-Intro-To-HARK-Buffer-Stock-Model.ipynb::Cell 8
FAILED Gentle-Intro-To-HARK-Buffer-Stock-Model.ipynb::Cell 9
FAILED Gentle-Intro-To-HARK-Buffer-Stock-Model.ipynb::Cell 10
FAILED Gentle-Intro-To-HARK-Buffer-Stock-Model.ipynb::Cell 11
FAILED Gentle-Intro-To-HARK-Buffer-Stock-Model.ipynb::Cell 12
FAILED Gentle-Intro-To-HARK-Buffer-Stock-Model.ipynb::Cell 13
FAILED Gentle-Intro-To-HARK-Buffer-Stock-Model.ipynb::Cell 15
FAILED Gentle-Intro-To-HARK-PerfForesightCRRA.ipynb::Cell 0
FAILED Gentle-Intro-To-HARK-PerfForesightCRRA.ipynb::Cell 1
FAILED Gentle-Intro-To-HARK-PerfForesightCRRA.ipynb::Cell 3
FAILED Gentle-Intro-To-HARK-PerfForesightCRRA.ipynb::Cell 4
FAILED Gentle-Intro-To-HARK-PerfForesightCRRA.ipynb::Cell 5
FAILED Gentle-Intro-To-HARK-PerfForesightCRRA.ipynb::Cell 6
FAILED Gentle-Intro-To-HARK-PerfForesightCRRA.ipynb::Cell 7
FAILED Gentle-Intro-To-HARK-PerfForesightCRRA.ipynb::Cell 8
FAILED Gentle-Intro-To-HARK-PerfForesightCRRA.ipynb::Cell 9
FAILED Gentle-Intro-To-HARK-PerfForesightCRRA.ipynb::Cell 10
FAILED Gentle-Intro-To-HARK-PerfForesightCRRA.ipynb::Cell 11
FAILED IncExpectationExample.ipynb::Cell 0
FAILED IncExpectationExample.ipynb::Cell 1
FAILED IncExpectationExample.ipynb::Cell 4
FAILED IndShockConsumerType.ipynb::Cell 0
FAILED IndShockConsumerType.ipynb::Cell 2
FAILED IndShockConsumerType.ipynb::Cell 3
FAILED IndShockConsumerType.ipynb::Cell 4
FAILED IndShockConsumerType.ipynb::Cell 5
FAILED IndShockConsumerType.ipynb::Cell 6
FAILED IndShockConsumerType.ipynb::Cell 7
FAILED IndShockConsumerType.ipynb::Cell 8
FAILED IndShockConsumerType.ipynb::Cell 9
FAILED IndShockConsumerType.ipynb::Cell 11
FAILED IndShockConsumerType.ipynb::Cell 12
FAILED IndShockConsumerType.ipynb::Cell 14
FAILED KeynesFriedmanModigliani.ipynb::Cell 0
FAILED KeynesFriedmanModigliani.ipynb::Cell 2
FAILED KeynesFriedmanModigliani.ipynb::Cell 3
FAILED KeynesFriedmanModigliani.ipynb::Cell 10
FAILED KeynesFriedmanModigliani.ipynb::Cell 12
FAILED KeynesFriedmanModigliani.ipynb::Cell 13
FAILED LifeCycleModelTheoryVsData.ipynb::Cell 0
FAILED LifeCycleModelTheoryVsData.ipynb::Cell 3
FAILED LifeCycleModelTheoryVsData.ipynb::Cell 4
FAILED LifeCycleModelTheoryVsData.ipynb::Cell 5
FAILED LifeCycleModelTheoryVsData.ipynb::Cell 7
FAILED LifeCycleModelTheoryVsData.ipynb::Cell 8
FAILED LifeCycleModelTheoryVsData.ipynb::Cell 9
FAILED LifeCycleModelTheoryVsData.ipynb::Cell 15
FAILED Micro-and-Macro-Implications-of-Very-Impatient-HHs.ipynb::Cell 0
FAILED Micro-and-Macro-Implications-of-Very-Impatient-HHs.ipynb::Cell 1
FAILED Micro-and-Macro-Implications-of-Very-Impatient-HHs.ipynb::Cell 2
FAILED Micro-and-Macro-Implications-of-Very-Impatient-HHs.ipynb::Cell 3
FAILED Micro-and-Macro-Implications-of-Very-Impatient-HHs.ipynb::Cell 4
FAILED Micro-and-Macro-Implications-of-Very-Impatient-HHs.ipynb::Cell 5
FAILED Micro-and-Macro-Implications-of-Very-Impatient-HHs.ipynb::Cell 6
FAILED Micro-and-Macro-Implications-of-Very-Impatient-HHs.ipynb::Cell 7
FAILED MPC-Out-of-Credit-vs-MPC-Out-of-Income.ipynb::Cell 1
FAILED MPC-Out-of-Credit-vs-MPC-Out-of-Income.ipynb::Cell 2
FAILED MPC-Out-of-Credit-vs-MPC-Out-of-Income.ipynb::Cell 3
FAILED MPC-Out-of-Credit-vs-MPC-Out-of-Income.ipynb::Cell 4
FAILED MPC-Out-of-Credit-vs-MPC-Out-of-Income.ipynb::Cell 5
FAILED MPC-Out-of-Credit-vs-MPC-Out-of-Income.ipynb::Cell 7
FAILED MPC-Out-of-Credit-vs-MPC-Out-of-Income.ipynb::Cell 8
FAILED MPC-Out-of-Credit-vs-MPC-Out-of-Income.ipynb::Cell 10
FAILED Nondurables-During-Great-Recession.ipynb::Cell 0
FAILED Nondurables-During-Great-Recession.ipynb::Cell 2
FAILED Nondurables-During-Great-Recession.ipynb::Cell 3
FAILED Nondurables-During-Great-Recession.ipynb::Cell 4
FAILED Nondurables-During-Great-Recession.ipynb::Cell 9
FAILED PerfForesightCRRA-Approximation.ipynb::Cell 0
FAILED PerfForesightCRRA-Approximation.ipynb::Cell 1
FAILED PerfForesightCRRA-Approximation.ipynb::Cell 2
FAILED PerfForesightCRRA-Approximation.ipynb::Cell 3
FAILED PerfForesightCRRA-Approximation.ipynb::Cell 4
FAILED PerfForesightCRRA-Approximation.ipynb::Cell 5
FAILED PerfForesightCRRA-Approximation.ipynb::Cell 6
FAILED PerfForesightCRRA-Approximation.ipynb::Cell 7
FAILED PerfForesightCRRA-SavingRate.ipynb::Cell 0
FAILED PerfForesightCRRA-SavingRate.ipynb::Cell 1
FAILED Structural-Estimates-From-Empirical-MPCs-Fagereng-et-al.ipynb::Cell 1
FAILED Structural-Estimates-From-Empirical-MPCs-Fagereng-et-al.ipynb::Cell 3
FAILED Structural-Estimates-From-Empirical-MPCs-Fagereng-et-al.ipynb::Cell 6
FAILED Structural-Estimates-From-Empirical-MPCs-Fagereng-et-al.ipynb::Cell 8
FAILED TractableBufferStock-Interactive.ipynb::Cell 0
FAILED TractableBufferStock-Interactive.ipynb::Cell 1
FAILED TractableBufferStock-Interactive.ipynb::Cell 2
FAILED TractableBufferStock-Interactive.ipynb::Cell 3
===================== 132 failed, 66 passed, 1 warning in 42.73s ======================

**Comment by llorracc** [comment]
Caused by old version of econ-ark having been installed.
