### ISSUE TITLE
Binder does not rebuild docker image when HARK@master changes

### ISSUE THREAD

**Issue by Mv77** [econ-ark/DemARK#158]
I noticed that the link to the DCEGM DemARK at [econ-ark](https://econ-ark.org/materials/dcegm-upper-envelope) is broken. The reason is the bug that was fixed by [this PR](https://github.com/econ-ark/HARK/pull/990/files). The puzzling behavior is that the bug is fixed in HARK@master!

This has led @llorracc and me to think that MyBinder does not update its docker image when any of its required packages are updated. Doubtless, if we were to change the version of HARK that was required, it would know that it needed rebuilding, but since its using `git+git://github.com/econ-ark/hark@master`, it has no way to know when the repo has been updated.

Does somebody know how to force Binder to rebuild its Docker image, even if it thinks nothing has changed?

**Comment by MridulS** [comment]
> Does somebody know how to force Binder to rebuild its Docker image, even if it thinks nothing has changed?

Mybinder builds new images only if there is a new commit on the repo being built (i.e the DemARK repo). If you would like to force a build you can push an "empty" commit.
```
git commit --allow-empty -m "trigger new mybinder build "
git push origin master  # assuming you can push directly to the DemARK repo.
```
