### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by alanlujan91** [econ-ark/DemARK#195]
Every few days there's a build error for windows py=3.10, which usually resolves itself after re-running the job. 

<img width="560" alt="image" src="https://user-images.githubusercontent.com/5382704/220220992-322a149f-ff37-478b-aff1-cbc14135f137.png">

**Comment by MridulS** [comment]
Hmm, looks like these errors are coming from:
```
ERROR notebooks/IncExpectationExample.ipynb::Cell 0 - RuntimeError: Kernel didn't respond in 60 seconds
ERROR notebooks/IncExpectationExample.ipynb::Cell 1 - RuntimeError: Kernel didn't respond in 60 seconds
ERROR notebooks/IncExpectationExample.ipynb::Cell 2 - RuntimeError: Kernel didn't respond in 60 seconds
ERROR notebooks/IncExpectationExample.ipynb::Cell 3 - RuntimeError: Kernel didn't respond in 60 seconds
ERROR notebooks/IncExpectationExample.ipynb::Cell 4 - RuntimeError: Kernel didn't respond in 60 seconds
```

my first knee-jerk reaction would be that the windows VM we get from github actions is just not powerful enough sometimes to run the notebook and that's why there is timeout maybe. But this may require some digging into.
