### ISSUE TITLE
binder/requirements.txt file not in Repo

### ISSUE THREAD

**Issue by AMonninger** [econ-ark/DemARK#205]
In the readme.txt file it says that a user should clone this Repo and install requirements.
The binder/requirements.txt file has been removed. I assume the user should install the requirements from the HARK repo.

**Comment by llorracc** [comment]
Mridul,

I think you (or maybe Cam?) updated Demark to use environment instead of
requirements.TXT.  Could you update instructions in the read me accordingly?

**Comment by llorracc** [comment]
@MridulS, can you do the unticked to-do in Cam's issue, and put somewhere the appropriate corresponding instructions for HARK (which still has a requirements.txt, not an environment.yml, approach to environments)?

Thanks

**Comment by MridulS** [comment]
This was fixed in https://github.com/econ-ark/DemARK/commit/7d77bdb4defbeca0096226ddb62303ea26e4ad37
