### ISSUE TITLE
Remove `FashionVictim` DEMARK or peg econ-ark dependency to 0.10.2

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/DemARK#77]
The FashionVictim DEMARK imports code from `HARK`:

https://github.com/econ-ark/DemARK/blob/master/notebooks/Fashion-Victim-Model.py#L52

After this, it appears to execute the exact same code that is in the Fashion-Victim-Model `main()` method:
https://github.com/econ-ark/DemARK/blob/master/notebooks/Fashion-Victim-Model.py#L123
https://github.com/econ-ark/HARK/blob/master/HARK/FashionVictim/FashionVictimModel.py#L414

In other words, this DEMARK is just a duplicate of what's in HARK, with some copy-and-pasted code.

FashionVictim is slated to be taken out of the HARK source library and into a HARK `examples/` directory.
https://github.com/econ-ark/HARK/issues/440

It has been argued that since FashionVictim is really a kind of tutorial documentation, not material for economics students, it's better for it to be in `examples/` than to be a DemARK.

Either:
 - The DemARK should be removed, or,
 - the DemARK `econ-ark` dependency should be pegged to version 0.10.2 so this DemARK can keep depending on HARK.

If we decide on the latter for some reason, I hope we put some thought into how to design this better to avoid code duplication across repositories.

**Comment by llorracc** [comment]
Let's make FashionVictim an "example" notebook, and remove it from the DemARK.

**Comment by llorracc** [comment]
@sbenthall will integrate this with https://github.com/econ-ark/HARK/issues/446

**Comment by sbenthall** [comment]
Fixed with https://github.com/econ-ark/DemARK/commit/e4a30aabde9f318dc86fd87753f63032dc5bc862#diff-c2365e874ecb861a659e5215ff17c338
