### ISSUE TITLE
ConsPortfolioModelDoc LaTeX / ipython issue

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/DemARK#82]
https://github.com/econ-ark/HARK/pull/442#issuecomment-565147757

**Comment by sbenthall** [comment]
I've transferred this to DemARK because it concerns code that's here.
When the DemARK is fixed, then we can move it to HARK/examples.

I've done some testing. There are two files related to this case:
`ConsPortfolioModelDoc.ipynb`
`ConsPortfolioModelDoc.py`

The notebook runs fine.
The `.py` file runs fine _if executed with_ `python ConsPortfolioModelDoc.py`

It's only running it with `ipython` that results in this problem.

So one question is: when do we want to support running `.py` files with `python`, and when with `ipython`?

**Comment by MridulS** [comment]
I have removed .py files from this repo as github has native support for notebook diffs now. This issue isn't relevant anymore.
