### ISSUE TITLE
TractableBufferStock-Interactive

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/DemARK#86]
@llorracc says here: https://github.com/econ-ark/HARK/pull/472#issuecomment-582010196

> While we're at it, though, let's change the name of
"TractableBufferStockQuickDemo" to "TractableBufferStock-Interactive" or
something like that.  (Open it and you'll see why).

**Comment by MridulS** [comment]
TractableBufferStock-Interactive already exists in DemARK
