### ISSUE TITLE
NameError: name 'deepcopy' is not defined

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/DemARK#94]
$ ipython ChangeLiqConstr.py 
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
~/projects/econ-ark/DemARK/notebooks/ChangeLiqConstr.py in <module>
     70 # + {"collapsed": true}
     71 # Make a copy of the example consumer
---> 72 KinkyExampleTighten = deepcopy(KinkyExample)
     73 
     74 # Now change the location of the borrowing constraint -- the consumer cannot borrow more than 0.2

NameError: name 'deepcopy' is not defined

**Comment by sbenthall** [comment]
This is still broken for me on `master`

**Comment by MridulS** [comment]
fixed in #99
